Update build_instructions.md
On Ubuntu 22.04 Libwebsockets uses a lot of low-level functions which are deprecated since OpenSSL 3.0.

Error:
/home/daniel/adi/libwebsockets/lib/tls/openssl/openssl-server.c: In function ‘lws_tls_server_certs_load’:
/home/daniel/adi/libwebsockets/lib/tls/openssl/openssl-server.c:401:9: error: ‘EC_KEY_new_by_curve_name’ is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
  401 |         ecdh = EC_KEY_new_by_curve_name(ecdh_nid);
      |         ^~~~
In file included from /usr/include/openssl/x509.h:33,
                 from /usr/include/openssl/ssl.h:31,
                 from /home/daniel/adi/libwebsockets/include/libwebsockets.h:250,
                 from /home/daniel/adi/libwebsockets/lib/core/private.h:130,
                 from /home/daniel/adi/libwebsockets/lib/tls/openssl/openssl-server.c:22:
/usr/include/openssl/ec.h:998:31: note: declared here
  998 | OSSL_DEPRECATEDIN_3_0 EC_KEY *EC_KEY_new_by_curve_name(int nid);
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~
/home/daniel/adi/libwebsockets/lib/tls/openssl/openssl-server.c:407:9: error: ‘EC_KEY_free’ is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
  407 |         EC_KEY_free(ecdh);
      |         ^~~~~~~~~~~
In file included from /usr/include/openssl/x509.h:33,
                 from /usr/include/openssl/ssl.h:31,
                 from /home/daniel/adi/libwebsockets/include/libwebsockets.h:250,
                 from /home/daniel/adi/libwebsockets/lib/core/private.h:130,
                 from /home/daniel/adi/libwebsockets/lib/tls/openssl/openssl-server.c:22:
/usr/include/openssl/ec.h:1003:28: note: declared here
 1003 | OSSL_DEPRECATEDIN_3_0 void EC_KEY_free(EC_KEY *key);
      |                            ^~~~~~~~~~~
/home/daniel/adi/libwebsockets/lib/tls/openssl/openssl-server.c:449:9: error: ‘EVP_PKEY_get1_EC_KEY’ is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
  449 |         EC_key = EVP_PKEY_get1_EC_KEY(pkey);
      |         ^~~~~~
In file included from /usr/include/openssl/x509.h:29,
                 from /usr/include/openssl/ssl.h:31,
                 from /home/daniel/adi/libwebsockets/include/libwebsockets.h:250,
                 from /home/daniel/adi/libwebsockets/lib/core/private.h:130,
                 from /home/daniel/adi/libwebsockets/lib/tls/openssl/openssl-server.c:22:
/usr/include/openssl/evp.h:1374:19: note: declared here
 1374 | struct ec_key_st *EVP_PKEY_get1_EC_KEY(EVP_PKEY *pkey);
      |                   ^~~~~~~~~~~~~~~~~~~~
/home/daniel/adi/libwebsockets/lib/tls/openssl/openssl-server.c:457:9: error: ‘EC_KEY_free’ is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
  457 |         EC_KEY_free(EC_key);
      |         ^~~~~~~~~~~
In file included from /usr/include/openssl/x509.h:33,
                 from /usr/include/openssl/ssl.h:31,
                 from /home/daniel/adi/libwebsockets/include/libwebsockets.h:250,
                 from /home/daniel/adi/libwebsockets/lib/core/private.h:130,
                 from /home/daniel/adi/libwebsockets/lib/tls/openssl/openssl-server.c:22:
/usr/include/openssl/ec.h:1003:28: note: declared here
 1003 | OSSL_DEPRECATEDIN_3_0 void EC_KEY_free(EC_KEY *key);
      |                            ^~~~~~~~~~~


The bug is fixed in the latest version of libwebsockets.

Additionally, the specified branch does not exist anymore.